### PR TITLE
Update managed object layout svg

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by MaxGraey** [comment]
@dcodeIO could you review this?

**Comment by dcodeIO** [comment]
Wondering how to model the `buffer`, `byteOffset` and `byteLength` relationship. Previously, these were `#` for protected, but now the access markers are inconsistent. This reminds me why we had `data`, `dataStart` and `dataLength` in the first place, because `TypedArray` would expose these as `buffer`, `byteOffset` and `byteLength` respectively but `Array` wouldn't. Makes me also wonder if we are exposing `buffer` of normal `Array`s now, which would be kinda unsafe.

**Comment by MaxGraey** [comment]
I think Array simply shouldn't extends from `ArrayBufferView`

**Comment by dcodeIO** [comment]
Perhaps, yeah. Would complicate a few things especially considering the loader which can't easily detect an `Array<T>` then because there's no common base class it can see in RTTI. If we made that change, the visibilities would be `+ buffer`, `+ byteOffset` and `+ byteLength`.

**Comment by dcodeIO** [comment]
To get back to this, I figured that we'll want a fix for `.buffer` pulled into `Array<T>` first so we can have an accurate diagram here. Makes me wonder whether the previous design of a separate internal `data`, that solved this problem, would be sensible to bring back.

**Comment by MaxGraey** [comment]
As I mentioned previous solution was not ideal especially because most of people used `data` and `dataLength` instead `buffer` and `byteLength`. `Array` shouldn't extends from `ArrayBufferView` and just have own private `buffer` reference. That's by the way will be architecture identical to JS / TS internal implementation

**Pull request closed without merging**
