### PR TITLE
Improve example of Overriding `abort`

### PR DESCRIPTION
**Pull request by webmaster128**
Closes AssemblyScript/assemblyscript#1065

### CODE REVIEW

**Comment by dcodeIO** [comment]
Let's use `assembly/index.ts` as the example, the default generated by `asinit`. Otherwise looks good.

**Comment by webmaster128** [comment]
👍 updated

**Comment by dcodeIO** [comment]
Thanks! :)

**Comment by webmaster128** [comment]
I have to say thank you :)

**Pull request merged**
